apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: GetVOIPLineMigrationDetails
  description:  |
    GetVOIPLineMigrationDetails service is part of the integration flow “Resource Provisioning.
spec:
  type: openapi
  owner: Developer
  lifecycle: demo
  system: Fixed Line
  definition:
    $text: https://github.com/baludeepak7/GetVOIPLineMigrationDetails/blob/main/getvoiplinemigrationdetails.yaml
    
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GetVOIPLineMigrationDetails
  description: |
    GetVOIPLineMigrationDetails service is part of the integration flow “Resource Provisioning.
  annotations:
    gitlab.com/project-id: '48576071'
    sonarqube.org/project-key: com.binpipe.spboot:demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: demo
  owner: Developer
  system: Fixed Line
  providesApis:
    - GetVOIPLineMigrationDetails
